[package]
name = "premain-libos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.26.2"
rcgen = "0.10.0"
time = "0.3.20"
